# Generated by Django 5.0.6 on 2024-06-20 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='student_name',
        ),
        migrations.AddField(
            model_name='question',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
