# Generated by Django 5.0.6 on 2024-06-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_responses_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='graded',
            field=models.BooleanField(default=True),
        ),
    ]
